name: nag

channels:
  - vladsaveliev
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - python==3.6
  - snakemake-minimal
  - bcftools
  - tabix
  - ensembl-vep           # to annotate VCF for pVACseq
  - cmake                 # to install INTEGRATE-Neo
  - ucsc-gtftogenepred    # to prepare data for fusionBedpeAnnotator
  - ngs_utils
  - pyyaml
  - click
  - vcfanno               # for PoN
  - numpy
  - cufflinks             # for expression data for pVACseq
  # - pyensembl           # install with pip - conda version errors out (also needs gtfparse>1.1)
    #
  # Actively developed accompanying libraries
  - pip:
    - "--editable=git+https://github.com/umccr/hpc_utils#egg=hpc_utils"
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
    - "--editable=git+https://github.com/umccr/vcf_stuff#egg=vcf_stuff"
